### ISSUE TITLE
Update type declarations, should also work if context is undefined

### ISSUE THREAD

**Issue by DesignByOnyx** [ionic-team/stencil-postcss#15]
~~There are two issues with the way the component is today - I am wrapping them up in one issue as I am about to file a PR.~~

~~**Issue 1:** type declarations for `Diagnostic` are out of sync with stencil/core. Specifically the "level" and "type" properties need to be loosened into `string` instead of the enum which is there currently. This is the same change which has already [been applied in stencil/sass](https://github.com/ionic-team/stencil-sass/commit/f3ad33b3de65f6cb66df67ebfd06a44eb572bb88).~~

~~**Issue 2:**~~ 

> **UPDATE:** The type definitions were updated after I opened this issue and my PR. Hence the strikethrough above.

In my project, I am importing css from a 3rd party module like this:
```css
@import '@our-company/global-styles';
```
but the imported CSS file is not being processed due to [`context` being undefined](https://github.com/ionic-team/stencil-postcss/blob/master/src/index.ts#L16). By moving the context check to a different place, I am able to import our CSS successfully (you will see in the PR). If you have a better suggestion on how to fix this, I will gladly implement it.

**Comment by splitinfinities** [comment]
Can you help my out by creating a reproduction repo with the latest versions of @stencil/core and @stencil/postcss?

**Comment by DesignByOnyx** [comment]
I haven't worked with Stencil for quite some time. I'll go ahead and close this as I don't remember how to reproduce this.
