### ISSUE TITLE
PostCSS plugin autoprefixer requires PostCSS 8

### ISSUE THREAD

**Issue by baticodes** [ionic-team/stencil-postcss#28]
Hi mates,

I'm getting the folowing error after installing postCSS and autoprefixer following the steps detailed on readme. Current version of postCSS is 7:

`Build Error
PostCSS plugin autoprefixer requires PostCSS 8. Update PostCSS or downgrade this plugin. at Processor.normalize...`

```
npm install @stencil/postcss --save-dev
npm install autoprefixer @types/autoprefixer --save-dev
```

(Edit)
Those are my dev dependencies:
```
"devDependencies": {
    "@stencil/postcss": "^1.0.1",
    "@stencil/sass": "^1.3.2",
    "@types/autoprefixer": "^9.7.2",
    "autoprefixer": "^10.0.0"
  }
```

**Comment by kalepail** [comment]
Yep same here.

**Comment by jptcnde** [comment]
v9 will work, yarn add autoprefixer@9

**Comment by badpenguin** [comment]
well i've tried with v9 but i get the following errors:
```
[ ERROR ]  postcss: src/global/app.css: src/global/app.css
           undefined

[ ERROR ]  postcss: node_modules/ionicons/dist/collection/components/icon/icon.css: node_modules/ionicons/dist/collection/components/icon/icon.css
           undefined
```

**Comment by illepic** [comment]
Noting here that [postcss-nested](https://github.com/postcss/postcss-nested) is throwing the same error.
