### ISSUE TITLE
Incompatible with tailwind 2 (postcss 8)

### ISSUE THREAD

**Issue by michaelkrog** [ionic-team/stencil-postcss#30]
Using stencil-postcss with tailwind 2 fails because postcss 8 is required.
https://tailwindcss.com/docs/installation#building-your-css

It is unable to find the css to do its work on.

Example output
```
[17:26.7]  generate outputs finished in 3.48 s  MEM: 386.8MB
[17:26.7]  aborted build, 6497ms  MEM: 386.8MB

[ ERROR ]  postcss: src/styles/bronco.css: src/styles/bronco.css
           undefined

```

Downgrading to tailwind 1.9 works fine.

**Comment by dtaalbers** [comment]
You can still use Tailwind CSS 2 by installing `2.0.1-compat` version for Tailwind. The `compat` version uses PostCSS 7. Doesn't take away though, that PostCSS in this plugin can be updated to PostCSS 8.

**Comment by jagreehal** [comment]
I've created a PR for this https://github.com/ionic-team/stencil-postcss/pull/31
