### ISSUE TITLE
Cannot set property 'ES6Promise' of undefined

### ISSUE THREAD

**Issue by bitflower** [ionic-team/stencil-postcss#6]
Hey guys,

I'm getting a 
```
Uncaught TypeError: Cannot set property 'ES6Promise' of undefined
    at app.core.js:50
    at app.core.js:50
```

<img width="1499" alt="bildschirmfoto 2018-03-22 um 11 06 55" src="https://user-images.githubusercontent.com/6666636/37764161-33524fb6-2dc1-11e8-8d94-af6db8f1f761.png">

when editing the *.pcss file of a component in standard `npm run dev` watch mode.

I happens in Chrome as soon as I save the pcss file. 

When I stop the dev server and `npm run dev` again all is good and no errors occur.

Component app-dashboard.tsx:
```javascript
import {
  Component
} from '@stencil/core';

@Component({
  tag: 'app-dashboard',
  styleUrl: 'app-dashboard.pcss.pcss'
})
export class AppDashboard {
  public render(): JSX.Element {
    return (
      <app-translate entry='dashboard.index' />
    );
  }
}
``` 

app-dashboard.pcss (before):
```
app-dashboard {
  display: block;
}

```

app-dashboard.pcss (after):
```
app-dashboard {
  display: block;
  opacity: 0;
  transition: 175ms opacity cubic-bezier(.4, 0, .2, 1);

  &.hydrated {
    opacity: 1;
  }
}
```

It's happing inside a copy of @bfmatei's [boilerplate](https://github.com/bfmatei/stencil-boilerplate)

Latest `@stencil/core` 0.7.5, `@stencil/postcss` is 0.0.4.

**Comment by bitflower** [comment]
Still there with `@stencil/core` 0.7.8

**Comment by jagreehal** [comment]
To recreate the issue clone my repo https://github.com/jagreehal/stencil-boilerplate

Run in es5 mode, change the following in package.json - “start”: “npm run dev --es5".

Then make a change in style file (src/components/my-app/my-app.scss)

**Comment by bfmatei** [comment]
Hello!

I investigated this issue. It is not related to the PostCSS plugin, but with Stencil. It is covered by this: https://github.com/ionic-team/stencil/issues/676
