### ISSUE TITLE
Non-component styles fail to rebuild

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/stencil-postcss#7]
```
@stencil/core@0.7.18
@stencil/postcss@0.0.4
```

We're having an issue with this plugin where external stylesheets—stylesheets that aren't linked directly to a component via `styleUrl` in the `@Component` decorator—are not included when the styles are rebuilt.

Those styles work and are included correctly on the initial build, just not on rebuilds. I've got a simple recreation of the issue in [this repo](https://github.com/camwiegert/stencil-postcss-external-rebuild-issue).

**Comment by gavinmcfarland** [comment]
I'm experiencing the same issue. In order for postcss-import to work the imported file needs to be process by postcss but Stencil is not aware that the two files are linked and so despite Stencil watching all files for changes the file where the CSS are being imported never gets updated.

**Comment by B-Stewart** [comment]
+1 this is still an issue with latest @stencil/core 1.16.2 and @stencil/postcss 1.0.1
